[terminal.shell]
program = "zsh"


[selection]
save_to_clipboard = true

[font]
size = 13
normal = { family = "CaskaydiaMono Nerd Font", style = "Regular" }
bold = { family = "CaskaydiaMono Nerd Font", style = "Bold" }
italic = { family = "CaskaydiaMono Nerd Font", style = "Italic" }

[window]
decorations = "none"
dynamic_padding = true
padding = { x = 4, y = 4 }

[general]
import = ["themes/bloodmoon.toml"]

# to install the themes
# mkdir -p ~/.config/alacritty/themes
# git clone https://github.com/alacritty/alacritty-theme ~/.config/alacritty/themes
