# Here you list all the shortcuts. To reload, turn the extension off and on.
#
# The shortcuts may be defined in two ways:
#
# 1. Run-or-raise form: shortcut,command,[wm_class],[title]
#        * `wm_class` and `title` are optional and case sensitive
#        * if none is set, lowercased launch `command` is compared with lowercased windows wm_classes and titles
#
# 2. Run only form: shortcut,command
#
#
# In fact, the full form is `shortcut[ char][:mode],command,[wm_class],[title]`
# while `char` allows you to use layered shortcuts and `mode` to further specify circumstances.
#
# =================
# Run or raise form
# =================
#
#
# This line cycles any firefox window (matched by "firefox" in the window title) OR if not found, launches new firefox instance.

# Blank lines are allowed. Line starting with "#" means a comment.
# Now delete these shortcuts and put here yours.
# How to know wm_class? Using xprop or the looking glass tool, see README.md


<Super>b,brave-browser.desktop,Brave-browser,
<Super>c,google-chrome.desktop,Google-chrome,
<Super>a,Alacritty.desktop,Alacritty,
<Super>g,jetbrains-goland-90aac271-9fd7-4127-998f-f975cbe83282.desktop,jetbrains-goland,
<Super>s,slack.desktop,Slack,
