-- Keymaps are automatically loaded on the VeryLazy event
-- Default keymaps that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/keymaps.lua
-- Add any additional keymaps here
-- local map = LazyVim.safe_keymap_set
--
-- map("n", "<C-h>", "<cmd>ZellijNavigateLeft!<cr>", { desc = "Go to Left Window", remap = true })
-- map("n", "<C-j>", "<cmd>ZellijNavigateDown<cr>", { desc = "Go to Lower Window", remap = true })
-- map("n", "<C-k>", "<cmd>ZellijNavigateUp<cr>", { desc = "Go to Upper Window", remap = true })
-- map("n", "<C-l>", "<cmd>ZellijNavigateRight!<cr>", { desc = "Go to Right Window", remap = true })
