#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

if [[ $(autorandr --current) == "ntb_dell" ]]; then	
	bspc monitor HDMI1 -d I II III IV V VI
	bspc monitor eDP1 -d VII VIII IX X
elif [[ $(autorandr --current) == "ntb_only" ]]; then	
	bspc monitor eDP1 -d I II III IV V VI VII VIII IX X
elif [[ $(autorandr --current) == "ntb_only_integrated" ]]; then	
	bspc monitor "eDP-1" -d I II III IV V VI VII VIII IX X
elif [[ $(autorandr --current) == "ntb_dell_integrated" ]]; then	
	bspc monitor "HDMI-1" -d I II III IV V VI
	bspc monitor "eDP-1" -d VII VIII IX X
elif [[ $(autorandr --current) == "ntb_only_nvidia" ]]; then	
	bspc monitor "eDP-1-1" -d I II III IV V VI VII VIII IX X
elif [[ $(autorandr --current) == "ntb_dell_nvidia" ]]; then	
	bspc monitor "HDMI-1-1" -d I II III IV V VI
	bspc monitor "eDP-1" -d VII VIII IX X
fi

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a firefox desktop='^2'
#bspc rule -a Brave-browser desktop='^2'
bspc rule -a discord desktop='^9'
bspc rule -a mplayer2 state=floating
bspc rule -a Yad state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Emacs state=tiled

bspc config bottom_padding	0
bspc config right_padding	0

# Border
bspc config focused_border_color        "#6c71c4"
bspc config normal_border_color         "#073642"
bspc config active_border_color         "#073642"

#
# Autostart
#
# Set display from arandr saved script
#sh ~/.screenlayout/monitor.sh &
#autorandr --change &
# Bar
~/.config/polybar/launch.sh &
# Notifications
/usr/bin/dunst &
# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# Wallpaper
nitrogen --restore &
# Picom
picom -CGb &
# Dex
dex -a -s /etc/xdg/autostart/:~/.config/autostart/ &
# Network Applet
nm-applet --indicator &
# Cursor
xsetroot -cursor_name left_ptr 16 &
